### PR TITLE
Update ClassBasedRoutingKeyResolver.php

### PR DESCRIPTION
**Pull request by holtkamp**
Allow other separator characters. Amazon SQS does not allow the (default) dots in queue names...

### CODE REVIEW

**Comment by holtkamp** [comment]
Guess this does not make sense as we can not influence how resolveRoutingKeyFor() is invoked. Need a separate RoutingKeyResolver for this...

**Comment by cmodijk** [comment]
What we could do is the following

```php
class ClassBasedRoutingKeyResolver implements RoutingKeyResolver
{
    private $separator;

    public function __construct($separator = '.')
    {
        $this->separator = $separator;
    }

    public function resolveRoutingKeyFor($message)
    {
        return str_replace(
            '\\',
            $this->separator,
            get_class($message)
        );
    }
}
```

**Comment by holtkamp** [comment]
An additional feature that "would be nice" / I found myself implementing, is allowing a prefix. 

**UseCase**
In our DTAP approach (Development, Test, Acceptation, Production) it is required to separate the Message Queues properly. Since a provider like Amazon SQS does not offer an (easy) way to create separate "projects" and using separate accounts / API credentials seems overkill: we prefix the Message Queues, for a class ```Project\Domain\Command\DoStuff``` this would result in queues like:

- development-Project-Domain-Command-DoStuff
- test-Project-Domain-Command-DoStuff
- acceptation-Project-Domain-Command-DoStuff
- production-Project-Domain-Command-DoStuff

So next to a separator, a prefix would be nice as well 😄

**Comment by holtkamp** [comment]
The rationale of

```php
is_object($message) ? get_class($message) : $message
```

is to be able to determine a queue name easily:

```php
$queueName = $queueResolver->resolveRoutingKeyFor(\Project\Domain\Command\Name::class);
```

When the queue name is known, it is easier to consume messages from specific queues only

**Comment by holtkamp** [comment]
@cmodijk Anything missing for a merge?

**Comment by holtkamp** [comment]
@cmodijk shameless bump, encountered this again 😄

**Comment by cmodijk** [comment]
The prefix part is really specific to your use case and i would suggest to keep this class simple. Maybe ad a new one and use inversion to implement a prefix/suffix style helper like this.

```php
# We change the simple bus method to this 
class ClassBasedRoutingKeyResolver implements RoutingKeyResolver
{
    private $separator;

    public function __construct($separator = '.')
    {
        $this->separator = $separator;
    }

    public function resolveRoutingKeyFor($message)
    {
        return str_replace(
            '\\',
            $this->separator,
            get_class($message)
        );
    }
}

# Create a new class i'm not sure if this is something for this repo but this is a example
class PrefixBasedResolver implements RoutingKeyResolver
{
    private $parent;
    private $prefix;
    private $suffix;

    public function __construct(RoutingKeyResolver $parent, $prefix = null, $suffix = null)
    {
        $this->parent = $parent;
        $this->prefix = $prefix;
        $this->suffix = $suffix;
    }

    public function resolveRoutingKeyFor($message)
    {
        $message = '';

        if (isset($this->prefix)) {
            $message .= $this->prefix;
        }

        $message .= $this->parent->resolveRoutingKeyFor($message);

        if (isset($this->suffix)) {
            $message .= $this->prefix;
        }

        return $message;
    }
}

# In your case u can use this like this
new PrefixBasedResolver(new ClassBasedRoutingKeyResolver('-'), 'development-', '-more-stuff')
```

**Comment by holtkamp** [comment]
@cmodijk mmm, yeah, might be better to keep the default as simple as possible. 

Do you agree with this part though?

https://github.com/SimpleBus/Asynchronous/pull/9#issuecomment-270166175

**Comment by cmodijk** [comment]
> Do you agree with this part though?

Does this happen that the message provide is not a object? If so yes we should add this check.

**Comment by holtkamp** [comment]
>Does this happen that the message provide is not a object?

Yes, this allows us to:
- determine the Queue name for specific Commands (each type of Command has a different Queue)
- check this specific Queue for Messages and consume/process them

This can be handy when certain Commands (on a specific Queue) should be assigned a higher priority / should not be dealt with during office hours (database intensive processing), etc.

**Comment by cmodijk** [comment]
@holtkamp Yeah we could leave that in but it would still mean that this pull request needs a update to only be able to change the separator like I suggest earlier https://github.com/SimpleBus/Asynchronous/pull/9#issuecomment-269800765

**Comment by holtkamp** [comment]
@cmodijk would you accept a `PrefixBasedResolver` class in this repository?

Your comment states:

>Create a new class i'm not sure if this is something for this repo but this is a example

You want me to add such a class to a new PR?

**Comment by cmodijk** [comment]
> You want me to add such a class to a new PR?

Sure if you can update this PR i'm willing to merge it into repository as long as it is a new class.

**Comment by cmodijk** [comment]
@holtkamp Do you still need this issue, if so can you update the pull request?

**Comment by holtkamp** [comment]
mmm, thanks for the reminder, will try to work on it this week

**Comment by cmodijk** [comment]
@holtkamp No problem I did not had much time lately.

**Comment by holtkamp** [comment]
@cmodijk done! Separated the classes 🤓

**Comment by cmodijk** [comment]
@holtkamp Can you add a tests for this?

**Comment by holtkamp** [comment]
@cmodijk coming weeks probably not, maybe end of the year...

**Comment by holtkamp** [comment]
@cmodijk done, good you requested this, some serious stupidities were in my code 😨

**Comment by cmodijk** [comment]
After talking to @ruudk we are closing this we don't want to support this in the main repository. With the interfaces you are already able to support this in your own project. If you have any feedback or other suggestions please let us know.

**Comment by holtkamp** [comment]
> If you have any feedback or other suggestions please let us know.

mmm, thought now that is a well separated class this would not harm anyone to get merged...

**Pull request closed without merging**
